language: java
sudo: false
install: true

script: 
 # Building the project
 - mvn compile
 - mvn test
 - mvn package

 # Testing the project
 - mvn verify

env:
  global:
    - MY_ENV=false

 # Deploying the project
deploy:
  on:
    branch: master
    condition: $MY_ENV = "true"
