language: java
sudo: false
install: true

script: 
 # Building the project
 - mvn compile
 - mvn test
 - mvn package

 # Testing the project
 - mvn verify

 # Deploying the project
 - deploy:
   on:
     branch: deploy
 # repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter

