language: java
sudo: false
install: true

script: 
 # Building the project
 - mvn compile
 - mvn test
 - mvn package

 # Testing the project
 - mvn verify
 
 
 
jobs:
  include:
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"

 # Deploying the project
# deploy
  # provider: heroku
  # api_key: "8ba59df0-bb57-4150-b2b6-2084cc48dda0"
  # on:
    #branch: master
 # Skipping a deployment with the  provider because this branch is not permitted

