language: java
sudo: false
install: true

script: 
 # Building the project
 - mvn compile
 - mvn test
 - mvn package

 # Testing the project
 - mvn verify

 # Deploying the project
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
# Skipping a deployment with the  provider because this branch is not permitted
